### ISSUE TITLE
IDEA: A small logo (square-like)

### ISSUE THREAD

**Issue by thomasvvugt** [gofiber/docs#67]
I had an idea to create a small, square form factor, logo of Fiber.
I was thinking about having the three identifiable blue stripes and maybe the letter F.
This logo could be useful for i.e. favicons and icons or avatars.
Let me know what you thing about this idea!

**Comment by koddr** [comment]
I did this at earlier Feb 2020 (when Fiber gain only 100 stars on GH). Also tried to make only stripes or only **F** or something else.

Result: only full logo can give information at this moment, because Fiber is still young and unknowing. And "_three identifiable blue stripes and maybe the letter F_" – it's bad idea to populate this brand right now.

Fiber is not Facebook, who can place **f** and everyone knows "_that's Facebook_".

**Comment by thomasvvugt** [comment]
After reviewing the old logo, I now fully get your feedback. Also, the origin of the three blue stripes never came to my mind. Maybe we can open re-open this issue in the future when the brand comes with more popularity. Thanks @koddr !
